apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  containers:
  - command: ['sh','-c']
    args:
      - echo 'hello';
        sleep 3600; 
    image: busybox
    name: multi-1
    resources: {}
  - command: ['sh','-c']
    args:
      - echo 'hello';
        sleep 3600; 
    image: busybox
    name: multi-2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
