apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  initContainers:
  - image: busybox:1.28
    name: busybox 
    command: ["sh","-c"]
    args: ["wget -O /work-dir/index.html http://neverssl.com/online"]
    resources: {}
    volumeMounts:
      - mountPath: /work-dir
        name: empty-dir
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html 
        name: empty-dir
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: empty-dir
      emptyDir: {} 
status: {}
